### ISSUE TITLE
Thiết kế mũ

### ISSUE THREAD

**Issue by mainguyenanhvu** [nmcntt2-cntn2016/project1-anonymous#2]
- Tìm hiểu mũ bảo hiểm (chất liệu, mô hình) thông dụng tại Việt Nam cho 2 loại người dùng: Người dùng phổ thông, Người dùng motor. => Lựa chọn và phác họa mô hình cho mũ.
- Tìm hiểu các thiết bị: (mô hình, khối lượng, giá tiền, công nghệ)

           1. Pin (Pin đội, Pin bộ) (khe sạc, hiển thị lượng pin, pin liền hay rời)
           2. Khe cắm thẻ nhớ
           3. Hộp đen
           4. Loa
           5. Bluetooth
           6. Camera
           7. Micro
           8. Cảm biến va đập
           9. Định vị GPS 
          10. Bộ xử lý
          11. Bản mạch.
          12. Xác định mũ có đang được sử dụng
          13. Thiết bị chống nước
   * Nếu một trong các thiết bị trên bị hư có thể thay thế không? Bằng cách nào?
- Tìm hiểu: ngưỡng va đập gây nguy hiểm cho con người, các vị trí thường xuyên bị va đập.
- Tìm hiểu:  Các tác động của mũ đối với người dùng: Khối lượng, hoạt động các thiết bị, .... 
**DEADLINE**: 27/03/2017

**Comment by mainguyenanhvu** [comment]
**VẼ PHÁC HỌA TRÊN GIẤY**
- Chọn 2 - 3 loại mũ bảo hiểm để thiết kế.
- Vị trí đặt các thiết bị trên từng loại mũ (phân bố khối lượng, các vị trí ít bị tác động khi va chạm).
- Hình dạng các thiết bị để phù hợp với mũ.
- Bản thiết kế kỹ thuật mạch điện trong mũ.
        **CHUYỂN BẢN THIẾT KẾ VÀO MÁY  TÍNH**

**DEADLINE**: 05/04/2017

**Comment by Nam403** [comment]
1. Về pin, theo tìm hiểu thì pin Li-po sẽ phù hợp với mũ hơn với một số tính năng ưu việt như: có tính tùy biến, nhẹ, dung lượng cao, khó bị cháy. 
2. Khe cắm thẻ nhớ tích hợp để có thể sử dụng thẻ nhớ linh hoạt, khi cần có thể lấy thẻ nhớ ra ngoài để thực hiện kiểm tra dữ liệu.
3. Camera 8 megapixel kết hợp đèn plash
4. Xác định loại mũ thông dụng ở Việt Nam:
- Loại mũ bảo vệ nửa phần đầu ở trên, độ an toàn khá thấp, mũ dễ trượt khỏi đầu.
- Loại để hở mặt và cằm, che chắn phần sau và độ an toàn cao hơn loại mũ nửa đầu nhưng không phổ biến bằng.
*** Loại mũ trùm kín đầu ít người sử dụng, chỉ dành chủ yếu cho dân phượt, những người lái mô tô phân khối lớn.

**Comment by Nam403** [comment]
Khảo sát giá linh kiện:
- Về camera, theo giá hiện nay một camera 8MP của iphone 5S có giá từ 100.000 - 160.000đ
- Về pin: 
* Pin điện thoại: khoảng 150.000đ - 200.000đ
* Pin laptop: giá khoảng 350.000đ - 450.000đ
* Pin ipad: 150.000-600.000đ. (Pin ipad 3/4 11560mAh Original có giá khoảng 550.000đ, pin ipad mini2 6471mAh có giá 140.000đ)
- Về loa: 100.000đ - 200.000đ
- Về khe cắm thẻ nhớ: Tham khảo công nghệ đầu đọc thẻ nhớ (đầu đọc chất lượng tốt: 100.000 - 200.000đ)
- Về sử dụng Blutooth: Phụ kiện âm thanh di động tạo kết nối blutooth với tầm kết nối 35m, có giá 60.000-70.000đ).
- Sử dụng bo mạch chủ dành cho smartphone (200.000đ - 1000.000đ)

**Comment by Nam403** [comment]
- Bộ cảm biến va đập: dựa trên bộ cảm biến va đập chống trộm (250.000 - 400.000đ)
- Hộp đen: trên 1tr. -_-
-> Nên nghĩ đến phương án sử dụng thẻ nhớ nếu như muốn giảm giá thành cũng như kích thước.
