### ISSUE TITLE
Làm web giới thiệu sản phẩm

### ISSUE THREAD

**Issue by mainguyenanhvu** [nmcntt2-cntn2016/project1-anonymous#3]
**DEADLINE**: 26/03/2017

**Comment by mainguyenanhvu** [comment]
- Giao diện
- Nội dung giới thiệu
- Ý tưởng, công nghệ sử dụng, quy trình, vấn đề, giải pháp. 
https://github.com/NMCNTT2-Anonymous/NMCNTT2-Anonymous.github.io

**Comment by mainguyenanhvu** [comment]
Trang chủ | Giới thiệu | Dự án | Liên hệ 
   |                                      |           |
   v                                    V          v
Show post mới          sổ ra mục  example@gmail.com

**Comment by mainguyenanhvu** [comment]
Tôi có tìm được trang cho sourse code. Thấy mẫu này cũng khá đẹp. Mình sửa lại xíu là ổn.
https://www.djangosites.org/s/eventcreative-org/ (3)
https://www.djangosites.org/s/www-academicstoday-ca/ (2)
https://www.djangosites.org/s/collegedive-in/ (4)
https://www.djangosites.org/s/hallway-yuyu54-com/ (5)
https://www.djangosites.org/s/www-renooble-com/ (1)

**Comment by hmhuan1012tg** [comment]
https://w3layouts.com/
Tham khảo bên này đi, t thấy bên đây cũng đc đó.

**Comment by mainguyenanhvu** [comment]
https://w3layouts.com/skating-sports-category-flat-bootstrap-responsive-web-template/

**Comment by hmhuan1012tg** [comment]
https://w3layouts.com/car-hub-automobile-category-bootstrap-responsive-web-template/
Cái n thì sao? T thấy cái trên hơi nhiều phần quá sợ ghi ko hết. T nghĩ cái n đơn giản vs gọn hơn.

**Comment by mainguyenanhvu** [comment]
Được á. Triển luôn đi

**Comment by hmhuan1012tg** [comment]
Vậy t tải template lên github luôn cho dễ chỉnh sửa

**Comment by mainguyenanhvu** [comment]
okie
